services:
  backend:
    build:
      dockerfile: ./BE/Dockerfile.prod
    ports:
      - 8000:8000

  frontend:
    build:
      dockerfile: ./FE/Dockerfile.dexter.prod
    ports:
      - 80:80
    volumes:
      - /app/FE/node_modules
    depends_on:
      - backend
  proxy:
    image: nginx:1.19
    ports:
      - 8094:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend