services:
  backend:
    build:
      dockerfile: ./BE/Dockerfile.prod
    ports:
      - "8000:8000"

  frontend:
    build:
      dockerfile: ./FE/Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - /app/FE/node_modules
    depends_on:
      - backend