# Use official Deno image
FROM denoland/deno:latest AS be

# Set working directory
WORKDIR /app/BE

# Copy backend files
COPY ./BE .

WORKDIR /app/

COPY ./types ./types

WORKDIR /app/BE

# Install Python dependencies
RUN apt-get update && apt-get install -y python3 python3-pip \
    && pip install -r requirements.txt --break-system-packages

RUN deno compile --no-check --allow-all --env-file=.env.prod api.ts

# Expose backend port
EXPOSE 8000

# Run the Deno server
CMD ["./api"]