# Use official Deno image
FROM denoland/deno:latest AS be

# Set working directory
WORKDIR /app/BE

# Copy backend files
COPY ./BE .

RUN deno install

WORKDIR /app/

COPY ./types ./types

WORKDIR /app/BE

# Install Python dependencies
RUN apt-get update && apt-get install -y && apt-get install -y procps python3 python3-pip \
    && pip install -r requirements.txt --break-system-packages

RUN deno cache --allow-import api.ts

EXPOSE 8000

CMD ["python3", "./scripts/initServer.py", "--prod"]