# Use Node.js image for building
FROM node:20 AS fe

# Set working directory
WORKDIR /app/FE

COPY FE/package*.json .

RUN npm install

# Copy frontend files
COPY ./FE .

WORKDIR /app/

COPY ./types ./types

WORKDIR /app/FE

CMD ["npm", "start"]