# Use Node.js image for building
FROM node:20 AS fe

# Set working directory
WORKDIR /app/FE

COPY FE/package*.json .

RUN npm install

# Copy frontend files
COPY ./FE .

WORKDIR /app/

COPY ./types ./types

WORKDIR /app/FE

RUN npm run build

FROM nginx:alpine
COPY --from=fe /app/FE/dist /usr/share/nginx/html
COPY --from=fe /app/FE/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]